#!/usr/bin/env sh

FANCTL=/usr/bin/fanctl

# Check if i8kctl exists and is executable
if [ ! -x "$I8KCTL" ]; then
    echo "Error: fanctl needs $FANCTL"
    exit 1
fi

if [[ "$1" == "-h" ]]; then
    echo "Usage: fan [left right]"
    exit 0
elif [ "$#" -gt 0 ]; then
    exec "$I8KCTL" "fan" "$@"
else
    CHOICE=$(whiptail --title "Fan Speed Selection" --menu "Choose your option" 15 60 4 \
    "1" "Off" \
    "2" "Low" \
    "3" "High" \
    "4" "Intense" 3>&1 1>&2 2>&3)

    exitstatus=$?

    if [ "$exitstatus" = 0 ]; then
        case $CHOICE in
            1)
                # Off: Both fans off
                COMMANDS=("fan 0 0")
                ;;
            2)
                # Low: Left Speed: 2400, Right Speed: 0
                COMMANDS=("fan 0 0" "sleep 1" "fan 1 -1")
                ;;
            3)
                # High: Left Speed: 5500 Right Speed: 5500
                COMMANDS=("fan 1 1")
                ;;
            4)
                # Intense: Left Speed: 6400 Right Speed: 5800
                COMMANDS=("fan 2 2")
                ;;
            *)
                echo "Invalid choice"
                exit 1
                ;;
        esac

        # Privilege determination
        if [ "$(id -u)" != "0" ]; then
            SUDO="sudo"
        else
            SUDO=""
        fi

        # Execute the commands
        for CMD in "${COMMANDS[@]}"; do
            if [[ "$CMD" == "sleep "* ]]; then
                SLEEP_DURATION="${CMD#sleep }"
                sleep "$SLEEP_DURATION"
            else
                $SUDO "$I8KCTL" $CMD
            fi
        done
    else
        echo "User exited."
        exit 1
    fi
fi
